apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-p5-48xlarge-static
spec:
  replicas: 0
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 86400s
    consolidationPolicy: WhenEmpty
    terminationGracePeriod: 1h
  template:
    metadata:
      labels:
        ai.eks.amazonaws.com/amiFamily: ${ami_family}
        accelerator: nvidia
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu-p5-48xlarge-static
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["p5.48xlarge"]
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
      taints:
        - effect: NoSchedule
          key: nvidia.com/gpu
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu-p5-48xlarge-static
spec:
  ${indent(2, ec2nodeclass)}
  ${indent(2, lookup(jsondecode(efa_network_interfaces), "p5.48xlarge", ""))}
