apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-ml-obs-ref-arch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/awslabs/ai-ml-observability-reference-architecture.git
      path: chart
      targetRevision: HEAD
      helm:
        releaseName: kube-prometheus-stack
        values: |
          opensearch-operator:
            fullnameOverride: opensearch-operator
          mcp:
            enabled: ${observability_mcp_enabled}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
