apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-inference-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api-inference-extension
    targetRevision: v${version}
    path: config/crd
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
