apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mpi-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow/mpi-operator.git
    targetRevision: v${version}
    path: manifests/overlays/standalone
  destination:
    server: https://kubernetes.default.svc
    namespace: mpi-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules