apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynamo-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia/ai-dynamo
    chart: dynamo-platform
    targetRevision: ${version}
    helm:
      # dynamo operator manage CRDs via a pre-install/pre-upgrade hook Job via server-side apply.
      skipCrds: true
      values: |
        ${user_values_yaml}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${namespace}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    # Ignore differences in webhook configurations during upgrades
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionWebhook
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingAdmissionWebhook
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
