apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: ${version}
    helm:
      values: |
        # Target only nodes running AL2023 AMIs
        nodeSelector:
          amiFamily: al2023

        # Enable GPU Feature Discovery (default: false)
        gfd:
          enabled: true

        # Configure Node Feature Discovery components
        nfd:
          worker:
            tolerations:
              - operator: "Exists"
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
