apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-dra-driver-gpu
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia
    chart: nvidia-dra-driver-gpu
    targetRevision: ${version}
    helm:
      apiVersions:
        - "v1/resource.k8s.io"
      values: |
        ${user_values_yaml}
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-dra-driver-gpu
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
