apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selenium-grid
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://www.selenium.dev/docker-selenium
    chart: selenium-grid
    targetRevision: 0.52.0
    helm:
      parameters:
        - name: chromeNode.enabled
          value: "true"
        - name: chromeNode.replicas
          value: "3"
        - name: firefoxNode.enabled
          value: "false"
        - name: firefoxNode.replicas
          value: "1"
        - name: edgeNode.enabled
          value: "false"
        - name: edgeNode.replicas
          value: "1"
        - name: ingress.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: selenium-grid
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
